export const list= {
    "recommendations" : 
        [
            "React",
            "JavaScript",
            "CSS",
            "HTML",
            "Next.js",
            "Node.js",
            "TypeScript",
            "GraphQL",
            "Redux",
            "Tailwind CSS",
            "Webpack",
            "Babel",
            "Vue.js",
            "Angular",
            "Svelte",
            "Python",
            "Django",
            "Flask",
            "FastAPI",
            "SQL",
            "NoSQL",
            "MongoDB",
            "PostgreSQL",
            "MySQL",
            "SQLite",
            "Git",
            "GitHub",
            "GitLab",
            "Bitbucket",
            "Docker",
            "Kubernetes",
            "AWS",
            "Azure",
            "Google Cloud",
            "Heroku",
            "Firebase",
            "Netlify",
            "Vercel",
            "Jamstack",
            "Machine Learning",
            "Data Science",
            "Artificial Intelligence",
            "Cybersecurity",
            "Blockchain",
            "Quantum Computing",
            "Internet of Things",
            "DevOps",
            "Agile",
            "Scrum",
            "Project Management",
            "UI/UX Design",
            "Graphic Design",
            "Photography",
            "Writing",
            "Marketing",
            "SEO",
            "Content Creation",
            "Entrepreneurship",
            "Finance",
            "Investing",
            "Personal Development",
            "Productivity",
            "Mindfulness",
            "Mental Health",
            "Fitness",
            "Nutrition",
            "Travel",
            "Cooking",
            "Baking",
            "Gardening",
            "DIY",
            "Home Improvement",
            "Fashion",
            "Beauty",
            "Art",
            "Music",
            "Movies",
            "Books",
            "History",
            "Science",
            "Mathematics",
            "Education",
            "Languages",
            "Culture",
            "Politics",
            "Philosophy",
            "Sociology",
            "Psychology",
            "Sports",
            "Gaming",
            "Technology",
            "Innovation",
            "Health",
            "Environment",
            "Sustainability",
            "Astronomy",
            "Space Exploration",
            "Physics",
            "Chemistry",
            "Biology"
        ]
}